In [4]:
#import pandas as pd
#import numpy as np
#import time
#from datetime import datetime
#import dask
#import dask.dataframe as dd

In [5]:
from pack.get_data import import_data, format_data

#from pack.format_data import format_data

In [6]:
dff=import_data()
dff.head()

,#RIC,Domain,Date-Time,GMT Offset,Type,Price,Volume,Buyer ID,Bid Price,Bid Size,...,Ask Size,Qualifiers,Exch Time,Tick Dir.,Total Volume,Bid Spread,Ask Spread,Accumulated Ask Order Size,Accumulated Bid Order Size,Average Price
0,AMP.N,Market Price,2006-06-06 11:00:17.869244+00:00,-4,Mkt. Condition,NaN,NaN,NaN,NaN,NaN,...,NaN,[PRC_QL2],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AMP.N,Market Price,2006-06-06 13:30:56.169608+00:00,-4,Quote,NaN,NaN,NaN,45.21,6.0,...,1.0,NaN,13:30:56.000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AMP.N,Market Price,2006-06-06 13:30:56.449863+00:00,-4,Trade,45.21,6300.0,NaN,NaN,NaN,...,NaN,NaN,13:30:56.000000000,v,NaN,NaN,NaN,NaN,NaN,NaN
3,AMP.N,Market Price,2006-06-06 13:30:57.715407+00:00,-4,Quote,NaN,NaN,NaN,45.15,1.0,...,1.0,NaN,13:30:57.000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AMP.N,Market Price,2006-06-06 13:30:58.212446+00:00,-4,Quote,NaN,NaN,NaN,45.15,1.0,...,1.0,NaN,13:30:58.000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:

dff=format_data(dff)
dff.head()

,#RIC,Domain,Date-Time,GMT Offset,Type,Price,Volume,Buyer ID,Bid Price,Bid Size,...,Ask Spread,Accumulated Ask Order Size,Accumulated Bid Order Size,Average Price,Date1,hour,minute,second,date,date1
0,AMP.N,Market Price,2006-06-06 11:00:17.869244+00:00,-4,Mkt. Condition,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2006-06-06 11:00:17.869244+00:00,11,0,17,2006-06-06 11:00:17.869244+00:00,2006-06-06
1,AMP.N,Market Price,2006-06-06 13:30:56.169608+00:00,-4,Quote,NaN,NaN,NaN,45.21,6.0,...,NaN,NaN,NaN,NaN,2006-06-06 13:30:56.169608+00:00,13,30,56,2006-06-06 13:30:56.169608+00:00,2006-06-06
2,AMP.N,Market Price,2006-06-06 13:30:56.449863+00:00,-4,Trade,45.21,6300.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2006-06-06 13:30:56.449863+00:00,13,30,56,2006-06-06 13:30:56.449863+00:00,2006-06-06
3,AMP.N,Market Price,2006-06-06 13:30:57.715407+00:00,-4,Quote,NaN,NaN,NaN,45.15,1.0,...,NaN,NaN,NaN,NaN,2006-06-06 13:30:57.715407+00:00,13,30,57,2006-06-06 13:30:57.715407+00:00,2006-06-06
4,AMP.N,Market Price,2006-06-06 13:30:58.212446+00:00,-4,Quote,NaN,NaN,NaN,45.15,1.0,...,NaN,NaN,NaN,NaN,2006-06-06 13:30:58.212446+00:00,13,30,58,2006-06-06 13:30:58.212446+00:00,2006-06-06